apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer-app
          image: saurabhkaushik1206/customer-app-image:6
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          env:
            - name: DbContextSettings__ConferenceCallConnection
              # value: Server=10.104.0.18:5432;Database=customerdb;User Id=postgres; Pooling=true;Password=kaushik;
              value: Server=postgres-headless-service.default.svc.cluster.local:5432;Database=customerdb;User Id=postgres; Pooling=true;Password=kaushik;